config/routes.rb
Rails.application.routes.draw do

  get '/tasks/new', to: 'tasks#new', as: :new_task
  post '/tasks', to: 'tasks#create',as: :tasks

  get '/tasks', to: 'tasks#index'
  get '/tasks/:id', to: 'tasks#show', as: :task

  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch '/tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :destroy]
  def index
    @tasks = Task.all
  end

  def show
    @complete = @task.completed ? 'This task is completed 🙂' : 'This task is not completed 🙁'
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render 'new.html.erb'
    end
  end

  def edit; end

  def update
    @task = Task.update(task_params)
    if @task.update
      redirect_to task_path(@task)
    else
      render 'edit.html.erb'
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Imports -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/index.html.erb
<div class="content-container">
  <div class="container-flex">
    <h2>MY TASKS</h2>
    <div class="container-flex">
      <p class="grow">ADD NEW TASK</p>
      <%= link_to new_task_path do %> <i class="fas fa-plus icon"></i><% end %>
    </div>
  </div>



  <div class="container-tasks">
    <% @tasks.each do |task| %>
    <ul class="list-group">
      <li class="list-group-item border-0">
        <% if task.completed %>
          <i class="far fa-check-square"></i>
          <% else %>
          <i class="far fa-square"></i>
        <% end %>
        <%= link_to task_path(task) do%><%= task.title %><% end %>
        <%= link_to task_path(task), method: :delete, data: { confirm: 'Are you sure you want to delete?' } do %>
        <i class="fas fa-trash-alt icon mx-2"></i>
        <% end %>
      </li>

    </ul>
    <% end %>
  </div>

  <%= link_to new_task_path do %>
    <div class="backlink">
      BACK TO LIST
    </div>
  <% end %>

</div>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>

<h5><%= @task.details %></h5>

<h5><%= @complete %></h5>